/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.core;

import models.usuario.Usuario;
import views.empresa.ListaDeEmpresas;

/**
 *
 * @author akira
 */
public class Home extends javax.swing.JFrame {

    Usuario usuario = new Usuario("kassia", "akira", "181510");
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFundo = new javax.swing.JPanel();
        faixaMenu = new javax.swing.JPanel();
        txt_nome_titulo = new javax.swing.JLabel();
        jpl_opcao_usuario = new javax.swing.JPanel();
        jlb_icon_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        jpl_opcao_empresas = new javax.swing.JPanel();
        jlb_icon_empresas = new javax.swing.JLabel();
        txt_empresas = new javax.swing.JLabel();
        jpl_opcao_relatorios = new javax.swing.JPanel();
        jlb_icon_relatorios = new javax.swing.JLabel();
        txt_relatorios = new javax.swing.JLabel();
        jlb_sair = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanelFundo.setBackground(new java.awt.Color(178, 242, 236));
        JPanelFundo.setPreferredSize(new java.awt.Dimension(820, 509));
        JPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faixaMenu.setBackground(new java.awt.Color(47, 79, 79));

        txt_nome_titulo.setFont(new java.awt.Font("Merriweather Light", 1, 36)); // NOI18N
        txt_nome_titulo.setForeground(java.awt.Color.white);
        txt_nome_titulo.setText("Demanda Fácil");

        javax.swing.GroupLayout faixaMenuLayout = new javax.swing.GroupLayout(faixaMenu);
        faixaMenu.setLayout(faixaMenuLayout);
        faixaMenuLayout.setHorizontalGroup(
            faixaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faixaMenuLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(txt_nome_titulo)
                .addGap(277, 277, 277))
        );
        faixaMenuLayout.setVerticalGroup(
            faixaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faixaMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txt_nome_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        JPanelFundo.add(faixaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 140));

        jpl_opcao_usuario.setBackground(new java.awt.Color(0, 128, 128));

        jlb_icon_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-User.png"))); // NOI18N

        txt_usuario.setFont(new java.awt.Font("Merriweather Light", 1, 36)); // NOI18N
        txt_usuario.setForeground(java.awt.Color.white);
        txt_usuario.setText("Usuário");

        javax.swing.GroupLayout jpl_opcao_usuarioLayout = new javax.swing.GroupLayout(jpl_opcao_usuario);
        jpl_opcao_usuario.setLayout(jpl_opcao_usuarioLayout);
        jpl_opcao_usuarioLayout.setHorizontalGroup(
            jpl_opcao_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_usuarioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txt_usuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcao_usuarioLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jlb_icon_usuario)
                .addGap(65, 65, 65))
        );
        jpl_opcao_usuarioLayout.setVerticalGroup(
            jpl_opcao_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_usuarioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jlb_icon_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelFundo.add(jpl_opcao_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, 180));

        jpl_opcao_empresas.setBackground(new java.awt.Color(0, 128, 128));
        jpl_opcao_empresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpl_opcao_empresasMouseReleased(evt);
            }
        });

        jlb_icon_empresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Empresa Cliente-128.png"))); // NOI18N

        txt_empresas.setFont(new java.awt.Font("Merriweather Light", 1, 36)); // NOI18N
        txt_empresas.setForeground(java.awt.Color.white);
        txt_empresas.setText("Empresas");

        javax.swing.GroupLayout jpl_opcao_empresasLayout = new javax.swing.GroupLayout(jpl_opcao_empresas);
        jpl_opcao_empresas.setLayout(jpl_opcao_empresasLayout);
        jpl_opcao_empresasLayout.setHorizontalGroup(
            jpl_opcao_empresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_empresasLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jpl_opcao_empresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcao_empresasLayout.createSequentialGroup()
                        .addComponent(jlb_icon_empresas)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcao_empresasLayout.createSequentialGroup()
                        .addComponent(txt_empresas)
                        .addGap(30, 30, 30))))
        );
        jpl_opcao_empresasLayout.setVerticalGroup(
            jpl_opcao_empresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_empresasLayout.createSequentialGroup()
                .addComponent(jlb_icon_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_empresas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelFundo.add(jpl_opcao_empresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, 180));

        jpl_opcao_relatorios.setBackground(new java.awt.Color(0, 128, 128));

        jlb_icon_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Contabilidade-128.png"))); // NOI18N

        txt_relatorios.setFont(new java.awt.Font("Merriweather Light", 1, 36)); // NOI18N
        txt_relatorios.setForeground(java.awt.Color.white);
        txt_relatorios.setText("Relatórios");

        javax.swing.GroupLayout jpl_opcao_relatoriosLayout = new javax.swing.GroupLayout(jpl_opcao_relatorios);
        jpl_opcao_relatorios.setLayout(jpl_opcao_relatoriosLayout);
        jpl_opcao_relatoriosLayout.setHorizontalGroup(
            jpl_opcao_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_relatoriosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txt_relatorios)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcao_relatoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlb_icon_relatorios)
                .addGap(51, 51, 51))
        );
        jpl_opcao_relatoriosLayout.setVerticalGroup(
            jpl_opcao_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcao_relatoriosLayout.createSequentialGroup()
                .addComponent(jlb_icon_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_relatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelFundo.add(jpl_opcao_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 230, 180));

        jlb_sair.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Sair-26.png"))); // NOI18N
        jlb_sair.setText("Sair");
        jlb_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlb_sairMouseReleased(evt);
            }
        });
        JPanelFundo.add(jlb_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlb_sairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_sairMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlb_sairMouseReleased

    private void jpl_opcao_empresasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpl_opcao_empresasMouseReleased
        // TODO add your handling code here:
        ListaDeEmpresas listaEmpresas = new ListaDeEmpresas();
        usuario.setIdUsuario(3);
        listaEmpresas.setUsuario(usuario);
        listaEmpresas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jpl_opcao_empresasMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFundo;
    private javax.swing.JPanel faixaMenu;
    private javax.swing.JLabel jlb_icon_empresas;
    private javax.swing.JLabel jlb_icon_relatorios;
    private javax.swing.JLabel jlb_icon_usuario;
    private javax.swing.JLabel jlb_sair;
    private javax.swing.JPanel jpl_opcao_empresas;
    private javax.swing.JPanel jpl_opcao_relatorios;
    private javax.swing.JPanel jpl_opcao_usuario;
    private javax.swing.JLabel txt_empresas;
    private javax.swing.JLabel txt_nome_titulo;
    private javax.swing.JLabel txt_relatorios;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables

    public void setUsuario(Usuario usuario) {
        if(usuario != null){
            this.usuario = usuario;
        }
    }

    public Usuario getUsuario() {
        return usuario;
    }
}
