/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.empresa;

import controllers.control.empresa.EmpresaControl;
import javax.swing.JFrame;
import models.usuario.Usuario;

/**
 *
 * @author akira
 */
public class FormListaEmpresas extends javax.swing.JPanel {

    private Usuario usuario;
    private EmpresaControl control = new EmpresaControl();
    /**
     * Creates new form FormListaEmpresas
     */
    public FormListaEmpresas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Lista = new javax.swing.JPanel();
        jbl_nome_pesquisa = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_visualizar_empresa = new javax.swing.JButton();
        txt_pesquisa_empresa = new javax.swing.JTextField();
        btn_criar_empresa = new javax.swing.JButton();

        jbl_nome_pesquisa.setText("Informe o nome da empresa");

        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Chevron Esquerda-26.png"))); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_visualizar_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Ver detalhes-26.png"))); // NOI18N
        btn_visualizar_empresa.setText("Visualizar");
        btn_visualizar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visualizar_empresaActionPerformed(evt);
            }
        });

        txt_pesquisa_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisa_empresaActionPerformed(evt);
            }
        });
        txt_pesquisa_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisa_empresaKeyReleased(evt);
            }
        });

        btn_criar_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagens/icones/icons8-Mais-26.png"))); // NOI18N
        btn_criar_empresa.setText("Criar Empresa");
        btn_criar_empresa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_criar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criar_empresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ListaLayout = new javax.swing.GroupLayout(jPanel_Lista);
        jPanel_Lista.setLayout(jPanel_ListaLayout);
        jPanel_ListaLayout.setHorizontalGroup(
            jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ListaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ListaLayout.createSequentialGroup()
                        .addComponent(txt_pesquisa_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ListaLayout.createSequentialGroup()
                        .addGroup(jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_ListaLayout.createSequentialGroup()
                                .addComponent(jbl_nome_pesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btn_criar_empresa))
                            .addGroup(jPanel_ListaLayout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_visualizar_empresa)))
                        .addGap(24, 24, 24))))
        );
        jPanel_ListaLayout.setVerticalGroup(
            jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_criar_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbl_nome_pesquisa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisa_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_visualizar_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        control.setUsuario(getUsuario());
        control.returnHome();
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_visualizar_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visualizar_empresaActionPerformed
        
        control.setUsuario(getUsuario());
        control.returnPerfilEmpresa();
        /*PerfilEmpresa perfilEmpresa = new PerfilEmpresa();
        
        //perfilEmpresa.setObject(empresa);
        
        perfilEmpresa.setVisible(true);*/
        this.setVisible(false);
    }//GEN-LAST:event_btn_visualizar_empresaActionPerformed

    private void txt_pesquisa_empresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisa_empresaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_pesquisa_empresaKeyReleased

    private void btn_criar_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criar_empresaActionPerformed
        control.setUsuario(getUsuario());
        control.returnCadastroEmpresa();
        this.setVisible(false);
    }//GEN-LAST:event_btn_criar_empresaActionPerformed

    private void txt_pesquisa_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisa_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisa_empresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_criar_empresa;
    private javax.swing.JButton btn_visualizar_empresa;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel_Lista;
    private javax.swing.JLabel jbl_nome_pesquisa;
    private javax.swing.JTextField txt_pesquisa_empresa;
    // End of variables declaration//GEN-END:variables
    public void setUsuario(Usuario usuario) {
        if(usuario != null){
            this.usuario = usuario;
        }
    }

    public Usuario getUsuario() {
        return usuario;
    }
    
    public void setFrame(JFrame index) {
        if(index != null){
            this.index = index;
        }
    }

    public JFrame getFrame() {
        return index;
    }
}
